### ISSUE TITLE
Bulk operations?

### ISSUE THREAD

**Issue by mlouage** [MightyOrm/Mighty#15]
Hello

Is there support for bulk operations? If not, is it on the roadmap?

Many thanks.

Maarten

**Comment by mikebeaton** [comment]
`Save`, `Update` and `Delete` have versions which take multiple items.

Do they do what you need?

If so, you'd be correct to point out that this [isn't documented where it should be](https://mightyorm.github.io/Mighty/docs/crud-actions.html).

**Comment by mikebeaton** [comment]
Hi @mlouage,

Thoughts? Do these actually do what you needed?

I have self-assigned this with regards to the need to document that these variants exist.

**Comment by mlouage** [comment]
Hi @MikeBeaton 

Sorry for not getting back to you earlier. I must say I haven't looked at it any further, I switched to using plain ADO.NET. Maybe for future reference, is the bulk operation for insert for example, generating SQL or must I write it myself like with ADO.NET? 

In my specific case I use Postgres with Npgsql ADO.NET provider and I'm using the [binary copy](https://www.npgsql.org/doc/copy.html) to facilitate the bulk insert.

**Comment by mikebeaton** [comment]
Thanks for the update. :)

From following the link I can see that you're talking about bulk population of tables e.g. from binary data. No, Mighty doesn't and won't support that kind of bulk data transfer into databases - I was just talking about CRUD operations on multiple objects at once.

FWIW Yes, the operations I referred you to (like all the CRUD-style operations in Mighty) do write the SQL for you. (But Mighty equally supports fetching from custom SQL when that is what you need.)

Finally, since you're on PostgreSQL using Npgsql, I'll just mention that Mighty has code specifically to provide [automatic cursor dereferencing](https://mightyorm.github.io/Mighty/docs/cursors.html#postgresql-1) when used with Npgsql, which [no longer directly provides that](https://github.com/npgsql/npgsql/issues/438) itself - in case that's something you might need at any point.

**Comment by mlouage** [comment]
Thanks for taking the time for answering and providing context. I'm sure I will remember MightyOrm for a next project!
