### ISSUE TITLE
Number representation of enum in db to appropriate enum type in auto map

### ISSUE THREAD

**Issue by Kritner** [MightyOrm/Mighty#16]
I'm attempting to use stored procedures along with automapping to a type, where that type contains an enum.

The enum itself is of a byte type, as is the column, but attempting to do the auto mapping from the db column to the object property, an exception is raised:

```
fail: ...
      Invalid cast from 'System.Byte' to 'MyEnum'.
System.InvalidCastException: Invalid cast from 'System.Byte' to 'MyEnum'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.Byte.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Mighty.DataContracts.DataContractMemberInfo.SetValue(Object obj, Object value)
   at Mighty.MightyOrm`1.QueryNWithParams[X](DbCommand command, CommandBehavior behavior, DbConnection conne
ction, DbDataReader outerReader)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
...
```
I can get around this by doing the mapping manually with a cast working with the dynamic directly and for all columns, but is there a way to do it otherwise when working with enums?

Note I don't know if i'm using the correct terminology or not, but when i'm saying auto map talking about relying on mighty orm with its `MightyOrm<T>` construction.

**Comment by mikebeaton** [comment]
I'm not 100% sure whether this is a bug or not, because C# doesn't let you assign a `byte` to an `enum : byte` without a cast.

E.g.

```c#
byte value = 3;
MyByteEnum target = value;
```

will not complile, with `Cannot implicitly convert type 'byte' to 'ByteEnum.MyByteEnum'. An explicit conversion exists (are you missing a cast?)`.

This is why Mighty is erroring here: a byte technically *isn't* a valid value for that column in C# (not just in Mighty), even though I agree it sounds like it should be.

To reiterate, as  you can see above Mighty is using `Convert.ChangeType`, which will work as long as you could have assigned what comes back from the database to what's in the column _without an explicit cast_ - but it's a decision of C# that here you can't. Exactly the same problem would happen with an integer from the db and a normal int enum.

To work around it, you have a choice to use a dynamic return value as you are doing, or alternatively you could write an intermediate strongly typed class with a `byte` member, and then add a constructor (or even a conversion operator) on the type you really want, which does the conversion from the intermediate type to the final type. Even that way, you'd still have to manually do the conversion on what comes back from the database every time (the advantage, if you need to care about such things, is that you'd still be using strongly typed objects everywhere).

I agree that these aren't ideal, but for the reasons above I'm currently thinking that I need to count this as a - reasonable! - feature request, not a bug.

**Comment by Kritner** [comment]
Oh yeah, I didn't intend to infer it was a bug, I just wasn't sure if there was some hooks already existing in mighty that could help me get around this particular issue.

I haven't looked into the mighty orm source in any significant way, but I was assuming it used reflection of some sort - if the type of the property being hydrated were of type enum, perhaps the `Enum.TryParse` or `Enum.Parse` methods could be utilized? https://docs.microsoft.com/en-us/dotnet/api/system.enum.tryparse?view=netstandard-2.1

**Comment by mikebeaton** [comment]
I've just looked a little more. I already have some code for assigning a non-enum value to an enum [in the codebase](https://github.com/MightyOrm/Mighty/blob/7e0a927873b528afbc74310122825ae0ad8225bb/src/ObjectExtensions.cs#L154-L163) - but it requires knowing the type of the enum you are writing to, it wouldn't just work for *any* enum. See also [this SO discussion](https://stackoverflow.com/questions/29482/how-to-cast-int-to-enum) - not all of which is about the difficult part of this, but some is. So even as a feature request, this might actually be quite non-trivial!

**Comment by mikebeaton** [comment]
It may be that a better approach, still as a new feature request, would be to support data mapping functions in (what is currently called) `SqlNamingMapper` - at the moment it only maps field <-> column names, it can't remap the actual data.

I'm not sure whether that would be a good thing to do or not... I hadn't come across any reason to think of needing it before - which doesn't mean there *aren't* other cases where it might be useful, as well as this.

**Comment by Kritner** [comment]
Ah yeah I guess my previous comment (and your https://github.com/MightyOrm/Mighty/issues/16#issuecomment-589089300) seem to be for cases when the enum string value is stored in the db, rather than the numeric value it represents?

**Comment by Kritner** [comment]
yeah the `SqlNamingMapper` was the only thing in the `MightyOrm<T>` construction parameters that seemed to be a place where it *could* have fit, but as you said it does not currently.

Rather than providing an additional mapping functionality, what about just an option for attempting to cast the property of type `enum` from the numeric column matching its name (or if using the `SqlNamingMapper` function?)  I'd imagine such an option could additionally support throwing or not depending on the result of the cast attempt?

**Comment by mikebeaton** [comment]
~That's what I'm trying to say. That is non trival, I believe, because there is nothing I can see that will let you just 'cast to enum', you have to know which _specific_ enum you are casting to, for each column.~
Scratch that, since Mighty does have the required type at the required time. Doh!

**Comment by mikebeaton** [comment]
Correct me if I'm wrong, but the problem is only for data coming in to Mighty, right? I'm guessing this should work already for data going out to the database?

**Comment by Kritner** [comment]
> Correct me if I'm wrong, but the problem is only for data coming in to Mighty, right? I'm guessing this should work already for data going out to the database?

I believe that is correct, don't think I've yet written code around saving an enum number value to the db.

**Comment by mikebeaton** [comment]
I've found the code that I'd need (this is just a demo of the right conversion done the right way, not code to drop directly into Mighty yet):

```c#
byte value = 1;
var t = typeof(MyByteEnum);
Assert.That(t.IsEnum, Is.True);
var target = Enum.ToObject(typeof(MyByteEnum), value);
Assert.That(target, Is.EqualTo(MyByteEnum.value_1));
```

I'm actually not sure whether enum columns will work on output at the moment. If they don't I'd need to add something similar for enum types on output too.

Partly as note to self: since it's cheap to check for - `t.IsEnum == true`, and I already have `t` - then it's something to add as default behaviour rather than a configurable option.

**Comment by shaneshaffer** [comment]
FWIW, enums going into the database work fine (at least with the int enums I've done), it is just when coming back from the database that this occurs, since there isn't an implicit conversion between the type stored in the database and the enum. "Just" need to explicitly cast the value to the enum type (which is what we're currently doing when we manually build objects from generic results because of this)

**Comment by mikebeaton** [comment]
@shaneshaffer - thanks for the heads up!

It turns out that I was over-simplifying to think of `Convert.ChangeType` as allowing you to convert all and only whatever you can assign without an explicit cast: even though it is not possible to assign from an enum's underlying type to the enum or vice versa without a cast, you *can* `Convert.ChangeType` in one of those directions, i.e. from an enum. This is documented at 'Notes to Callers' in [this Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/api/system.convert.changetype?view=netframework-4.8).

So Mighty just (turns out it is "just", when you find the right magic and if you already know the target type, which we do) needs the type of conversion code demoed above on output, and a couple of matching tests to confirm that it is then working in both directions.

**Comment by mikebeaton** [comment]
I've added support for this in version 3.1.0, up now on [NuGet](https://www.nuget.org/packages/Mighty).

**Comment by Kritner** [comment]
awesome, thanks @MikeBeaton I had just cracked open the code yesterday and started trying to get familiar with it for all of 10 minutes before the kids woke up and started causing a ruckus ;)

**Comment by mikebeaton** [comment]
Thanks for taking an interest in the codebase! :) Let me know if there are any issues.
