### ISSUE TITLE
Code docs/comments

### ISSUE THREAD

**Issue by brgrz** [MightyOrm/Mighty#3]
Add at least basic code comments to most methods so we at least have a general overview of what each method does (for instance, New() vs NewFrom() vs Insert() vs Save()).

**Comment by mikebeaton** [comment]
Yep, is in progress - version with this done, or much closer to completely done anyway, nearly ready to put up.

**Comment by brgrz** [comment]
Hey Mike, what is the status of this issue or the MightyORM project in general?

**Comment by mikebeaton** [comment]
Hi Marko,

I'm trying to get back to actively developing MightyOrm. I can justify this now since it will again be actively used in the new project I'm being paid to do at work.

I'm currently bringing all the test databases back to life (now on a different dev machine, after the nearly two years since I finished Mighty but decided I couldn't realistically support it even if I did release it; I believe I can now). The Massive tests never documented the non-standard changes to the test databases required to make them pass the Massive test suite (which I kept to confirm compatibility, but significantly extended in Mighty to cover all the very many new features). I'm doing that now.

I very much hope to have some significant progress and a new release to put up shortly. If I understood correctly then - apart from the currently low uptake of zero on this project (well, I've never really released it!) - then the main two issues blocking you from considering using it are:

- Async support
- Completed XML comments

Is that about right?

Thanks,

Mike

**Comment by brgrz** [comment]
Well, I do have a need for either your project or Massive (ported to .NET Core). I will try to port Massive to .NET Core myself over the weekend. Some features of Mighty certainly do look useful, SP supported will probably come in hand at some point in the future though I don't need it now.

**Comment by brgrz** [comment]
* Completed XML comments

FWIW we should be able to know what certain methods in a 3rd party library do without having an indepth knowledge of the code and XML comments enable that

**Comment by mikebeaton** [comment]
> FWIW we should be able to know what certain methods in a 3rd party library do without having an indepth knowledge of the code and XML comments enable that

I do know that! It's just a matter of one developer doing this when they can justify the work as being closely enough related to anyway-required work for their own company, or else in very limited personal time.

I've got Async for everything working now. This is pretty easily arguably better than Massive, since:
 - Everything, including the dynamic-only methods, like `Find`, `Max`, etc., have async versions in Mighty (`FindAsync`, `MaxAsync`, etc.)
 - `QueryAsync` returns `Task<IAsyncEnumerable<dynamic>>` (using [https://github.com/Dasync/AsyncEnumerable](https://github.com/Dasync/AsyncEnumerable) for now, until C# 8.0 async streams are released), instead of `Task<List<dynamic>>` as in Massive, so that we actually allow async reading of rows, as we should

I need to put in `CancellationToken` support (which I believe should be relatively simple, at least compared to the above changes), then put back together the sync and async versions, so that both exist together (I have initially just converted absolutely everything to async in a branch - which is in this repo) and then (finally) finish off the XML comments. (Regarding which, I have at last understood how to get VS to warn me for all public methods without XML comments.)

**Comment by mikebeaton** [comment]
This progress report now moved to #6

**Comment by mikebeaton** [comment]
@brgrz Mighty 3.0.3-beta with full XML comments is now up [on NuGet](https://www.nuget.org/packages/Mighty). I am working on finishing a documentation website.
